### ISSUE TITLE
https://kr8.rocks/ is down

### ISSUE THREAD

**Issue by ghostsquad** [apptio/kr8#52]
Just FYI, https://kr8.rocks/ doesn't load, and `www.kr8.rocks` gives a invalid certificate error:

```
Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for www.kr8.rocks. The certificate is only valid for the following names: *.github.io, github.io, *.github.com, github.com, www.github.com, *.githubusercontent.com, githubusercontent.com
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

**Comment by jess-belliveau** [comment]
Thanks @ghostsquad - we've been trying to decide if we revive it or just drop the site. Will have a chat with the team and make a call.

**Comment by brittonhayes** [comment]
Looks like a lot of people may be finding this tool from a [hacker news post](https://news.ycombinator.com/item?id=39101828) today that links to @jaxxstorm blog 😊

That blog points to kr8.rocks, which is obviously down, so just a friendly heads up it might be worth it to update that link to point here to capitalize on the hacker news traction!

**Comment by bbyers-apptio** [comment]
We no longer own the domain, so I've removed the links to kr8.rocks.  The site will still be available through the github pages site, https://apptio.github.io/kr8/
